when:
  - event: [push, tag, deployment]
    branch: main

steps:
  - name: frontend-build
    image: node:20
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm config set store-dir .pnpm-store
      - cd web
      - pnpm install
      - pnpm build

  - name: backend-build
    image: golang:latest
    commands:
      - go fmt ./...
      - go vet ./...
      - go mod tidy
      - go mod verify
      - go run test/cmd/mock.go # generate mock data
      - go test ./...
      - |
        for arch in amd64 arm64; do \
          GOOS=linux GOARCH=$arch go build \
          -ldflags "-s -w -X github.com/MizuchiLabs/ssh-nexus/tools/updater.Version=${CI_COMMIT_TAG} \
                          -X github.com/MizuchiLabs/ssh-nexus/tools/updater.BuildDate=${CI_PIPELINE_CREATED} \
                          -X github.com/MizuchiLabs/ssh-nexus/tools/updater.Commit=${CI_COMMIT_SHA}" \
          -o nexus-linux-$arch cmd/server/main.go; \
        done

  - name: container-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/${CI_REPO_OWNER,,}/${CI_REPO_NAME}
      registry: ghcr.io
      platforms: linux/amd64, linux/arm64
      username: ${CI_REPO_OWNER}
      auto_tag: true
      auto_labels: true
      password:
        from_secret: gh_token

  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --clean --skip=validate
    environment:
      GITHUB_TOKEN:
        from_secret: gh_token
    when:
      event: tag
